(
    STATE_CHON_LOAI_KHACH, STATE_NHAP_TEN_SP, STATE_CHON_PACKAGE, STATE_CHON_PACKAGE_PRODUCT,
    STATE_CHON_MA_SP, STATE_NHAP_MA_MOI,
    STATE_CHON_NGUON, STATE_NHAP_NGUON_MOI, STATE_NHAP_GIA_NHAP, STATE_NHAP_THONG_TIN,
    STATE_NHAP_TEN_KHACH, STATE_NHAP_LINK_KHACH, STATE_NHAP_SLOT,
    STATE_NHAP_GIA_BAN, STATE_NHAP_NOTE
) = range(15)

__all__ = [
    "STATE_CHON_LOAI_KHACH", "STATE_NHAP_TEN_SP", "STATE_CHON_PACKAGE", "STATE_CHON_PACKAGE_PRODUCT",
    "STATE_CHON_MA_SP", "STATE_NHAP_MA_MOI",
    "STATE_CHON_NGUON", "STATE_NHAP_NGUON_MOI", "STATE_NHAP_GIA_NHAP", "STATE_NHAP_THONG_TIN",
    "STATE_NHAP_TEN_KHACH", "STATE_NHAP_LINK_KHACH", "STATE_NHAP_SLOT",
    "STATE_NHAP_GIA_BAN", "STATE_NHAP_NOTE",
]
